//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundoCanjeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int Id { get; set; }
        public int UsuarioCalificador { get; set; }
        public int UsuarioCalificado { get; set; }
        public int Puntuacion { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
    }
}
